remote_theme: mmistakes/so-simple-theme
skin: "assets/css/skins/light.css"

# Site Settings
locale                   : "en"
title                    : "nantonel.github.io"
description              : "" 
url                      : "https://nantonel.github.io/"
mathjax: true

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-125824608-1"
    anonymize_ip         : false # true, false (default)

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Site Author
author:
  name             : "Niccolò Antonello"
  picture          : "/assets/images/yo2.png"
  email            : "niccolo.antonello@idiap.ch"
  links:
  - title: GitHub
    url: https://github.com/nantonel
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/niccol%C3%B2-antonello-48aa753b
    icon: fab fa-linkedin

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/nantonel
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/niccol%C3%B2-antonello-48aa753b
    icon: fab fa-linkedin
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
